/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agent/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Tools */
        get: operations["agent_tools_api_agent_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/tools/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Call */
        post: operations["agent_call_api_agent_tools_call_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment */
        get: operations["environment_api_environment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_jobs_get"];
        put?: never;
        /** Submit */
        post: operations["submit_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Output */
        get: operations["output_api_jobs__job_id__output_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema */
        get: operations["schema_api_openapi_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project */
        get: operations["project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/active-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate */
        post: operations["activate_api_projects__project_id__active_version_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attachment */
        post: operations["attachment_api_projects__project_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_projects__project_id__reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Specification */
        put: operations["specification_api_projects__project_id__spec_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_projects__project_id__versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/versions/{version_id}/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact */
        get: operations["artifact_api_projects__project_id__versions__version_id__artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/versions/{version_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostics */
        get: operations["diagnostics_api_projects__project_id__versions__version_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/versions/{version_id}/program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Program */
        get: operations["program_api_projects__project_id__versions__version_id__program_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/versions/{version_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_projects__project_id__versions__version_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proposals */
        get: operations["proposals_api_proposals_get"];
        put?: never;
        /** Execution Proposal */
        post: operations["execution_proposal_api_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proposal */
        get: operations["proposal_api_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decision */
        post: operations["decision_api_proposals__proposal_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_api_proposals__proposal_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_session_get"];
        put?: never;
        /** Login */
        post: operations["login_api_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings */
        get: operations["settings_api_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Model Profile */
        post: operations["create_model_profile_api_settings_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Model Profile */
        delete: operations["delete_model_profile_api_settings_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/profiles/{profile_id}/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Model Key */
        put: operations["set_model_key_api_settings_profiles__profile_id__key_put"];
        post?: never;
        /** Delete Model Key */
        delete: operations["delete_model_key_api_settings_profiles__profile_id__key_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/profiles/{profile_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Model Connection */
        post: operations["test_model_connection_api_settings_profiles__profile_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sfc/requirement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sfc */
        post: operations["sfc_api_sfc_requirement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivateVersion */
        ActivateVersion: {
            /** Expected Active Version Id */
            expected_active_version_id: string | null;
            /** Version Id */
            version_id: string;
        };
        /** AgentCall */
        AgentCall: {
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /** Call Id */
            call_id: string;
            /** Name */
            name: string;
            /** Project Id */
            project_id: string;
            /** Version Id */
            version_id?: string | null;
        };
        /** AgentToolResult */
        AgentToolResult: {
            /** Call Id */
            call_id: string;
            /** Content */
            content: string;
            /** Data */
            data: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Is Error */
            is_error: boolean;
            /** Name */
            name: string;
            /** Proposal Id */
            proposal_id?: string | null;
        };
        /** AgentTools */
        AgentTools: {
            /** Tools */
            tools: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
        };
        /** Artifact */
        Artifact: {
            /** Available */
            available: boolean;
            /** Filename */
            filename?: string | null;
            /** Id */
            id: string;
            /** Media Type */
            media_type?: string | null;
            /** Size */
            size?: number | null;
        };
        /** AttachmentUpload */
        AttachmentUpload: {
            /** Data Base64 */
            data_base64: string;
            /** Filename */
            filename: string;
        };
        /** AttachmentUploadResult */
        AttachmentUploadResult: {
            /** Attachment Id */
            attachment_id: string;
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** Capabilities */
        Capabilities: {
            /** Body Form */
            body_form: string;
            /** Operations */
            operations: {
                [key: string]: boolean;
            };
            /** Project Type */
            project_type?: string | null;
            /** Representations */
            representations?: string[];
            /** Sfc */
            sfc?: string | null;
            /** Structured Semantics */
            structured_semantics?: string | null;
        } & {
            [key: string]: components["schemas"]["JsonValue"];
        };
        /** DeviceCommentChange */
        DeviceCommentChange: {
            /** Address */
            address: string;
            /** After */
            after: string | null;
            /** Before */
            before: string | null;
        };
        /** Environment */
        Environment: {
            /** Desktop Execution Required */
            desktop_execution_required: boolean;
            /** Evidence */
            evidence: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Gateway Started */
            gateway_started: boolean;
            /** Passed */
            passed: boolean;
            /** Status */
            status: string;
        };
        /** ExecutionPreview */
        ExecutionPreview: {
            /** Action */
            action: string;
            /** Plan */
            plan?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Program */
            program: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** St */
            st: string | null;
            /** Svg */
            svg: string | null;
            /** Target Mode */
            target_mode: string;
            version: components["schemas"]["Version"];
            /** Version Id */
            version_id: string;
        };
        /** ExecutionProposal */
        ExecutionProposal: {
            /**
             * Action
             * @enum {string}
             */
            action: "gx_import" | "simulation" | "debug";
            /** Plan Id */
            plan_id?: string | null;
            /** Project Id */
            project_id: string;
            /** Request Id */
            request_id: string;
            /** Version Id */
            version_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Application */
            application: string;
            /** Status */
            status: string;
        };
        /** Job */
        Job: {
            /** Cancel Requested */
            cancel_requested?: boolean | null;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Last Sequence */
            last_sequence: number;
            /** Project Id */
            project_id?: string | null;
            /** Result */
            result?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Status */
            status: string;
            /** Updated At */
            updated_at?: string | null;
            /** Version Id */
            version_id?: string | null;
        };
        /** JobCreate */
        JobCreate: {
            /** Attachment Ids */
            attachment_ids?: string[];
            /**
             * Deep
             * @default true
             */
            deep: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "analysis" | "generation" | "agent" | "review" | "test_plan" | "debug_plan" | "gx_read" | "gx_inspect";
            /** Project Id */
            project_id: string;
            /** Request Id */
            request_id: string;
            /**
             * Response Language
             * @default zh-CN
             * @enum {string}
             */
            response_language: "zh-CN" | "en" | "ja";
            /** Run Id */
            run_id?: string | null;
            /**
             * Text
             * @default
             */
            text: string;
            /** Version Id */
            version_id?: string | null;
        };
        /** JobEvent */
        JobEvent: {
            /** Created At */
            created_at: string;
            /** Event Type */
            event_type: string;
            /** Job Id */
            job_id: string;
            /** Payload */
            payload?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Project Id
             * @default null
             */
            project_id: string | null;
            /** Sequence */
            sequence: number;
            /**
             * Version Id
             * @default null
             */
            version_id: string | null;
        };
        /** JobList */
        JobList: {
            /** Jobs */
            jobs?: components["schemas"]["Job"][];
        };
        /** JobOutput */
        JobOutput: {
            /** Analysis */
            analysis?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Audit */
            audit?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Base Version Id */
            base_version_id?: string | null;
            /** Content */
            content?: string | null;
            /** Generation */
            generation?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Plan */
            plan?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Plan Id */
            plan_id?: string | null;
            /** Proposal Id */
            proposal_id?: string | null;
            /** Proposal Ids */
            proposal_ids?: string[] | null;
            /** Report */
            report?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Report Id */
            report_id?: string | null;
            /** Spec Base Hash */
            spec_base_hash?: string | null;
            /** Spec Draft */
            spec_draft?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Status */
            status?: string | null;
        } & {
            [key: string]: components["schemas"]["JsonValue"];
        };
        JsonValue: unknown;
        /** LadderPreview */
        LadderPreview: {
            diff: components["schemas"]["LadderProgramDiff"];
            /** Ladder */
            ladder: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Program */
            program: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** St */
            st: string;
            /** Svg */
            svg: string;
            /**
             * Target Mode
             * @constant
             */
            target_mode: "ladder";
        };
        /** LadderProgramDiff */
        LadderProgramDiff: {
            /** Added */
            added: string[];
            /** After Network Count */
            after_network_count: number;
            /** After Network Order */
            after_network_order: string[];
            /** Base Version Id */
            base_version_id?: string | null;
            /** Before Network Count */
            before_network_count: number;
            /** Before Network Order */
            before_network_order: string[];
            /** Changes */
            changes: components["schemas"]["NetworkChange"][];
            /** Deleted */
            deleted: string[];
            /** Device Comment Changes */
            device_comment_changes: components["schemas"]["DeviceCommentChange"][];
            /** Device Comments Changed */
            device_comments_changed: boolean;
            /** Has Changes */
            has_changes: boolean;
            /**
             * Kind
             * @constant
             */
            kind: "ladder";
            /** Modified */
            modified: string[];
            /** Network Order Changed */
            network_order_changed: boolean;
            /** Property Changes */
            property_changes: {
                [key: string]: components["schemas"]["PropertyChange"];
            };
        };
        /** Login */
        Login: {
            /** Token */
            token: string;
        };
        /** ModelConnectionResult */
        ModelConnectionResult: {
            /** Error Code */
            error_code?: string | null;
            /** Message */
            message: string;
            /**
             * Status
             * @enum {string}
             */
            status: "connected" | "failed";
        };
        /** ModelConnectionTest */
        ModelConnectionTest: {
            /** Api Key */
            api_key?: string | null;
            profile?: components["schemas"]["ModelProfileUpdate"] | null;
        };
        /** ModelKeyUpdate */
        ModelKeyUpdate: {
            /** Api Key */
            api_key: string;
        };
        /** ModelProfile */
        ModelProfile: {
            /** Base Url */
            base_url?: string | null;
            /** Capabilities */
            capabilities?: {
                [key: string]: boolean;
            };
            /** Configured */
            configured: boolean;
            /**
             * Deletable
             * @default false
             */
            deletable: boolean;
            /** Generation Defaults */
            generation_defaults?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Id */
            id: string;
            /** Model */
            model?: string | null;
            /** Name */
            name?: string | null;
            /** Request Overrides */
            request_overrides?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** ModelProfileCreate */
        ModelProfileCreate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url: string;
            /** Capabilities */
            capabilities?: {
                [key: string]: boolean;
            };
            /** Generation Defaults */
            generation_defaults?: {
                [key: string]: unknown;
            };
            /** Id */
            id?: string | null;
            /** Model */
            model: string;
            /** Name */
            name: string;
            /** Request Overrides */
            request_overrides?: {
                [key: string]: unknown;
            };
        };
        /** ModelProfileUpdate */
        ModelProfileUpdate: {
            /** Base Url */
            base_url?: string | null;
            /** Capabilities */
            capabilities?: {
                [key: string]: boolean;
            } | null;
            /** Generation Defaults */
            generation_defaults?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: string;
            /** Model */
            model?: string | null;
            /** Name */
            name?: string | null;
            /** Request Overrides */
            request_overrides?: {
                [key: string]: unknown;
            } | null;
        };
        /** ModelSettings */
        ModelSettings: {
            /** Active Profile Id */
            active_profile_id?: string | null;
            /** Language */
            language: string;
            /** Profiles */
            profiles?: components["schemas"]["ModelProfile"][];
        };
        /** NetworkChange */
        NetworkChange: {
            /** After */
            after: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Before */
            before: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Comment */
            comment: string;
            /** Instruction Count */
            instruction_count: number;
            /**
             * Marker
             * @enum {string}
             */
            marker: "+" | "-" | "~";
            /** Network */
            network: string;
        };
        /** NullablePublicObject */
        NullablePublicObject: {
            [key: string]: components["schemas"]["JsonValue"];
        } | null;
        /** Project */
        Project: {
            /** Active Version Id */
            active_version_id?: string | null;
            /** Confirmed Spec */
            confirmed_spec?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Confirmed Spec Hash */
            confirmed_spec_hash?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Effort */
            effort?: string | null;
            /** Id */
            id: string;
            /** Messages */
            messages?: components["schemas"]["ProjectMessage"][];
            /** Name */
            name: string;
            /** Plc Model */
            plc_model: string;
            /** Reports */
            reports?: components["schemas"]["ReportSummary"][];
            /** Target Mode */
            target_mode: string;
            /** Updated At */
            updated_at?: string | null;
            /** Version Count */
            version_count: number;
            /** Versions */
            versions?: components["schemas"]["Version"][];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Plc Model
             * @default FX3U
             */
            plc_model: string;
            /**
             * Target Mode
             * @default ladder
             * @enum {string}
             */
            target_mode: "ladder" | "st";
        };
        /** ProjectList */
        ProjectList: {
            /** Projects */
            projects?: components["schemas"]["Project"][];
        };
        /** ProjectMessage */
        ProjectMessage: {
            /** Content */
            content?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Id */
            id?: string | null;
            /** Kind */
            kind?: string | null;
            /** Role */
            role?: string | null;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Effort */
            effort?: ("low" | "medium" | "high") | null;
            /** Name */
            name?: string | null;
            /** Plc Model */
            plc_model?: string | null;
            /** Target Mode */
            target_mode?: ("ladder" | "st") | null;
        };
        /** PropertyChange */
        PropertyChange: {
            after: components["schemas"]["JsonValue"];
            before: components["schemas"]["JsonValue"];
        };
        /** Proposal */
        Proposal: {
            /** Action */
            action: string;
            /** Base Version Id */
            base_version_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Result */
            result?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Status */
            status: string;
            /** Summary */
            summary?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProposalDecision */
        ProposalDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "accept" | "reject";
        };
        /** ProposalDecisionResult */
        ProposalDecisionResult: {
            job?: components["schemas"]["Job"] | null;
            proposal?: components["schemas"]["Proposal"] | null;
        };
        /** ProposalList */
        ProposalList: {
            /** Proposals */
            proposals?: components["schemas"]["Proposal"][];
        };
        /** PublicObject */
        PublicObject: {
            [key: string]: components["schemas"]["JsonValue"];
        };
        /** ReportSummary */
        ReportSummary: {
            /** Base Version Id */
            base_version_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Report Id */
            report_id: string;
            /** Report Type */
            report_type?: string | null;
            /** Status */
            status?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /** SFCInput */
        SFCInput: {
            /** Steps */
            steps: components["schemas"]["SFCStep"][];
        };
        /** SFCRequirement */
        SFCRequirement: {
            /**
             * Capability
             * @constant
             */
            capability: "requirement_input";
            /** Text */
            text: string;
        };
        /** SFCStep */
        SFCStep: {
            /** Action */
            action: string;
            /** Name */
            name: string;
            /**
             * Transition
             * @default
             */
            transition: string;
        };
        /** STPreview */
        STPreview: {
            diff: components["schemas"]["STTextDiff"];
            /** St */
            st: string;
            /**
             * Target Mode
             * @constant
             */
            target_mode: "st";
        };
        /** STTextDiff */
        STTextDiff: {
            /** After */
            after: string;
            /** Base Version Id */
            base_version_id?: string | null;
            /** Before */
            before: string;
            /** Has Changes */
            has_changes: boolean;
            /**
             * Kind
             * @constant
             */
            kind: "st";
            /** Unified Diff */
            unified_diff: string;
        };
        /** Session */
        Session: {
            /** Authenticated */
            authenticated: boolean;
            /** Csrf */
            csrf?: string | null;
            /** Read Only */
            read_only?: boolean | null;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Active Profile Id */
            active_profile_id?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Language */
            language?: ("zh-CN" | "en" | "ja") | null;
            profile?: components["schemas"]["ModelProfileUpdate"] | null;
        };
        /** SpecResult */
        SpecResult: {
            /** Hash */
            hash?: string | null;
            /** Issues */
            issues?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Spec */
            spec?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Valid */
            valid: boolean;
        };
        /** SpecUpdate */
        SpecUpdate: {
            /** Expected Hash */
            expected_hash: string | null;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
        };
        /** Validation */
        Validation: {
            /** Messages */
            messages?: string[];
            /** Status */
            status?: string | null;
        } & {
            [key: string]: components["schemas"]["JsonValue"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Version */
        Version: {
            /** Artifacts */
            artifacts?: components["schemas"]["Artifact"][];
            capabilities: components["schemas"]["Capabilities"];
            /** Confirmed Spec Hash */
            confirmed_spec_hash?: string | null;
            /** Confirmed Spec Snapshot */
            confirmed_spec_snapshot?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Created At */
            created_at?: string | null;
            /** Debug Attempts */
            debug_attempts?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | null;
            /** Gx Sync */
            gx_sync?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Id */
            id: string;
            /** Ir Sha256 */
            ir_sha256?: string | null;
            /** Lifecycle Status */
            lifecycle_status?: string | null;
            /** Parent Version Id */
            parent_version_id?: string | null;
            /** Plc Model */
            plc_model?: string | null;
            /** Simulator Runs */
            simulator_runs?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | null;
            /** Simulator Test Plans */
            simulator_test_plans?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | null;
            /** Summary */
            summary?: string | null;
            /** Target Mode */
            target_mode?: string | null;
            validation?: components["schemas"]["Validation"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agent_tools_api_agent_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTools"];
                };
            };
        };
    };
    agent_call_api_agent_tools_call_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCall"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentToolResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    environment_api_environment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    jobs_api_jobs_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_jobs__job_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    output_api_jobs__job_id__output_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schema_api_openapi_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_api_projects__project_id__active_version_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateVersion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attachment_api_projects__project_id__attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachmentUpload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentUploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_projects__project_id__reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicObject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    specification_api_projects__project_id__spec_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_api_projects__project_id__versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_api_projects__project_id__versions__version_id__artifacts__artifact_id__get: {
        parameters: {
            query?: {
                download?: boolean;
                theme?: ("light" | "dark") | null;
            };
            header?: never;
            path: {
                project_id: string;
                version_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnostics_api_projects__project_id__versions__version_id__diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicObject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    program_api_projects__project_id__versions__version_id__program_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NullablePublicObject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_projects__project_id__versions__version_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                version_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicObject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proposals_api_proposals_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execution_proposal_api_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionProposal"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proposal_api_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_api_proposals__proposal_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalDecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_proposals__proposal_id__preview_get: {
        parameters: {
            query?: {
                theme?: ("light" | "dark") | null;
            };
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LadderPreview"] | components["schemas"]["STPreview"] | components["schemas"]["ExecutionPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    login_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettings"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_model_profile_api_settings_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_profile_api_settings_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_model_key_api_settings_profiles__profile_id__key_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelKeyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_key_api_settings_profiles__profile_id__key_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_model_connection_api_settings_profiles__profile_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelConnectionTest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConnectionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sfc_api_sfc_requirement_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SFCInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SFCRequirement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
